version: "3.7"

services:
  iipsrv:
    build:
      context: .
      target: production
    init: true
    volumes:
      - ./artifacts:/opt/app/artifacts
    environment:
      - VERBOSITY=6
      - CORS=*
    ports:
      - 80:80
    networks:
      default:
        aliases:
          - iipsrv.test
